### ISSUE TITLE
[Modeling] Test 기체 팔 부분 재설계 요청

### ISSUE THREAD

**Issue by junhee0110** [junhee0110/DAYONE_drone#12]
# 이슈 개요
현재 팔 하나를 출력했는데, 모터를 감싸는 부분이 너무 얇습니다 ㅠㅠㅠ
아예 없애거나 두껍게 재 설계를 해야할것같아요...

# 이슈 발생 배경
방금 막 출력물 하나가 나왔는데 모터를 감싸는 부분이 뽀각하고 뿌러졌습니다...
다른 부분은 정상적으로 잘 나왔습니다. 튼튼하고요.
잘린 단면으로 보니 너무 얇아서 내부 채움이 충분하지 않게 된거같아요.

# 요청 사항 
우선 관련된 프린팅 설정을 바꿔서 다시 출력할 예정입니다.
하지만, 이로 인해 다른 부분의 퀄리티가 조금 바뀔 수 있어요... 심한 경우에는 효과가 없을 수도 있습니다.

이렇게 될 경우를 대비해서 모델을 어떻게 수정할지 미리 논의했으면 합니다.
나사 구멍이 있어서 그냥 감싸는 부분을 없애도 될것같기도 해요. 혹은 두께를 좀 늘리거나...
어떻게 생각하는지 코맨트 부탁드립니다.

**Comment by junhee0110** [comment]
# 새 출력물 보고
line width라는 설정을 25%정도 늘려 0.75mm로 설정했습니다. [Reference](https://3dprinterly.com/how-to-get-the-perfect-layer-height-setting/#What_is_the_Affect_of_Line_Width_on_Print_Strength)

현재 Nozzle Size가 0.6mm이므로 line width가 0.75가 되면 출력물이 다음과 같이 됩니다.
1. 강도가 높아짐
2. 출력 속도가 빨리짐
3. 정밀도가 떨어짐

정밀도에는 큰 문제가 없었으나, 출력물의 강도가 높아지며 인성이 감소하여 다시 한번 모터를 감싸는 부분이 부숴졌습니다.

# 프린팅 예정
아래의 3가지 시도를 해볼 예정입니다.
1. line width를 0.4mm로 조정 => 강도는 좀 떨어지지만, 인성이 커지길 기대
2. line width를 0.9mm로 조정 => 이렇게 출력하면, 벽과 내부 채움의 간격이 사라짐
3. line width를 0.6mm로 재 출력 => 첫 시도할때의 실수를 의심

아마 피드백을 주시기 전까지 1번 시도까지는 가능할 것 같습니다.. 또 보고 드리겠습니다.

**Comment by aquarius0122** [comment]
모터의 전선이 드론 안쪽 방향으로, 팔을 따라서 나와야 하는데 나사 구멍을 어떻게 뚫어야 원하는 각도로 고정할 수 있는지 먼저 확인해야 합니다. 나사 구멍을 조절하게 되면 (사방이 아니라) 전선이 나오는 일부분만 뚫어서 위에서 봤을 때 C자 형태로 수정할 수 있겠죠. 두께도 약간 늘리고 모따기 등을 활용하여 보강대도 설치할 예정입니다. 이렇게 모터 감싸는 부분을 수정하면 부러지는 문제는 충분히 해결할 수 있을 것입니다. 직접적으로 힘을 받는 부분이 아닌 외부 이물질을 막기 위해 설계한 것이므로 크게 신경쓰지 않아도 됩니다.
 
다만 프로토타입인 만큼 가공 과정에서 부러졌다면 부러진 대로 나사만 박아 사용해도 무방할 것입니다. 따라서 정밀도에 대해서 이번에는 크게 신경쓰지 않아도 될 것 같습니다.

이전에 이야기했었는데, 출력물의 원형 구멍이 제대로 표현되지 않는 문제가 있다고 알고 있습니다. 그렇게 되면 출력물의 나사 구멍이 실제 나사 고정에 부적합할 수도 있겠다는 생각이 드는데, Nozzle Size나 Line Width와 상관없이 FFF 방식 3D 프린팅 출력물에서 공통적으로 발생하는 문제입니다. 보강할 방법을 생각해 보면 좋을 것 같습니다.

이번 분할 출력물에서 접착과 조립의 편의를 위해 파트 사이에 사각기둥 형태의 요철을 도입했는데 실제로 조립해 보고 의견을 알려주길 바랍니다. 문제가 있다면 다른 방법을 생각해 보도록 하겠습니다.

**Comment by junhee0110** [comment]
우선 전선은 나사 구멍의 사이(?)로 나옵니다. 사진을 함께 첨부합니다.
그래서 실제 기체에서는 나사 구멍의 배열을 45도 회전시키면 선들이 팔을 타고 FC로 연결될 수 있을 것 같습니다. 그렇게 된다면 C자 형태로 가림막을 설치하는 것은 매우 좋은 아이디어 같습니다. 또한 C자 형태로 이어진다면 부러지는 문제도 보완이 될것같습니다 :)

지금 가림막이 부러지는 건... 진짜 툭 건들면 부러지는 수준입니다. 당장 테스트 기체에서는 큰 의미가 없는 것 같으니 부러지면 부러지는대로 사용을 하겠습니다.

가림막을 제외한 나머지 부분은 정밀도와 강도가 우수합니다! 말씀하신대로, 원형 구멍이 다른 부분과 비교했을때 조금 취약한 것은 사실이지만 원형을 유지하고있습니다. 그냥 사용해도 문제가 없을 것이라고 생각합니다. 이 역시 사진을 첨부하겠습니다. 이 정도면은 나사를 사용하는 과정에서 표면이 정돈될 것이라고 생각합니다. 다만, 문제가 될 법한 부분은 **내부 채움**과 **구멍** 사이의 간격이 조금 걱정되긴합니다만, 상부 표면에만 갈라짐이 조금 있어서 후가공을 하는 과정에서 채워넣을 수 있을 것 같습니다.

하나당 출력시간이 8시간으로, 아마 4개를 다 출력해서 월요일 워크타임에 보여드릴 수 있을 것 같습니다!

![아랫면에서 본 구멍](https://user-images.githubusercontent.com/56581018/106839736-2b4c6100-66e2-11eb-9576-84c6c8c9d50b.jpg)
![윗면에서 본 구멍](https://user-images.githubusercontent.com/56581018/106839745-2daebb00-66e2-11eb-8e99-8ae8bd150e3e.jpg)
![모터 사진](https://user-images.githubusercontent.com/56581018/106839746-2e475180-66e2-11eb-9a98-6b7e7fb724e2.jpg)
