### ISSUE TITLE
커뮤니케이션 파트의 양방향 통신 구현

### ISSUE THREAD

**Issue by coco0508** [junhee0110/DAYONE_drone#23]
# 작업 개요

-우선 양방향 통신 코드 구현은  코코아 팹에 RF모듈로 SPI통신 구현한 것이 있으니 이를 응용하면 될듯 합니다. 
-> 다만 실제 적용시 시리얼 모니터에서 코드상 serial.write 한 부분이 제대로 업로드 되지 않고 있고 RF통신이 이루어 지지 않는 다는 점에서 무작정 코드를 삽입하기 보다는 단방향 통신 부터 만져보면서 코드를 이해해야 할 것 같네요.  
-> 단방향 통신은 되지만 전달되는 데이터의 통제가 아직은 잘 되지 않고 있습니다. 
ex) 특정 숫자를 입력하면 전송이 멈추는 것 등이 안되고 있어요.

-SPI통신에서 SS(Slave Select, 현재 보드에서는 CSN)선은 마스터인 경우에는 어디에든 꽂아도 상관없지만 슬레이브일 경우에는 UNO기준으로 10번핀에 연결해야 한다고 하네요. 이유로는 마스터와 슬레이브를 구분하기 위해서 입니다. 현재 두 모듈 다 보드의 8번핀에 연결되어 있기 때문에 작업 진행에 따라 핀번호가 변경될 수 있습니다.

# 체크 리스트

확인 해야 할 것, 해야 할 것 리스트를 작성해주세요.
- [x] 단방향통신 구현
- [x] 양방향 통신 구현
- [ ] 전송 데이터 배열형태로 구현

**Comment by junhee0110** [comment]
멤버 교체로 커뮤니케이션 파트를 넘겨받았습니다.

통신은 다음과 같은 메커니즘으로 작동시킬 예정입니다.

#### 드론
- read한 정보가 없으면 계속해서 listen합니다.
- 정보가 올때까지 계속해서 listen하면 송수신 타이밍이 보정되는 것을 실험적으로 확인했습니다.
- 설정한 시간 만큼 정보를 받지 못한다면 timeout이 활성화 됩니다.
- timeout이 활성화 되면 드론이 설정한 함수를 수행하도록 합니다.
- 예를 들어 초기위치의 방향으로 비행하는 등의 함수입니다. 드론이 신호를 다시 잡을 수 있도록 합니다.

#### 조종기
- 드론으로 부터 정보를 받았는지 아닌지에 관계없이 계속해서 read와 write를 번갈아가면서 합니다.

**Comment by junhee0110** [comment]
위의 내용대로 코드 구현하였고 작동 확인했습니다!
이슈닫겠습니다!
