### ISSUE TITLE
지자기 센서를 활용한 YAW축 제어 질문

### ISSUE THREAD

**Issue by t1207a** [junhee0110/DAYONE_drone#9]
# 질문
X,Y,Z에 대한 출력 값 생성 후 제어기에 넣으면 각 축을 제어하게 될 것임 X,Y,Z에 대한 출력 값이 나오게 될 건데 이후에 어떻게 해야하는지에 대한 질문

**Comment by junhee0110** [comment]
# 답변

우선, 현재 지자기 센서로 YAW값을 추출하는 것은 이미 구현이 되있으니 걱정할 필요 없습니다!
간단히 원리를 설명하자면, 지구 자기장이 북쪽을 향한다는 것을 이용합니다.
 X,Y,Z축으로 분리된 자기장 값을 수학적으로 계산하여, 북쪽 기준으로 각도를 계산합니다.

우리 소스코드에서는 sensor파트에 gy86::get_heading()이라는 매소드로 구현이 되어있고, YAW값을 사용하기 위해서는 gy86::get_head() 매소드로 값을 return받으면 됩니다.
